[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["echo 'Skipping npm ci'"]

[phases.build]
cmds = ["npm install --legacy-peer-deps && npm run build"]

[start]
cmd = "npx serve -s build -l 3000"
